version: "3.5"

services:
  app_server:
    build: docker/app_server
    command: yarn dev-start
    volumes:
      - .:/app
    networks:
      - temporal-network
      - app-network
  code_server:
    build: docker/code_server
    command: code-server
    volumes:
      - .:/home/node/project
      - ./docker/code_server/config.yaml:/home/node/.config/code-server/config.yaml
    user: node
    networks:
      - dev-network
    expose:
      - 8080
  caddy:
    image: caddy
    depends_on: 
      - app_server
      - code_server
    networks:
      - dev-network
      - app-network
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile

# BEGIN temporal

  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:9.6
    networks:
      - temporal-network
    ports:
      - 5432:5432
  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    image: temporalio/auto-setup:1.6.3
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.6.3
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.6.0
    networks:
      - temporal-network
    ports:
      - 8088:8088
# END temporal

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
  app-network:
    driver: bridge
    name: app-network
  dev-network:
    driver: bridge
    name: dev-network
